const PrevExecCom = [
  {
    Term: "2021/2022",
    President: "Huthaifa Abdul Qader 🇯🇴",
    "VP of Internal Affairs": "Lamis Elsheikh 🇸🇩",
    "VP of Finances": "Konstantin Schrader 🇩🇪",
    "VP of Public Relations": "Deniz Devrim Kaya 🇹🇷",
    "VP of Exchanges": "Arsal Subbah Sadiq 🇵🇰",
    "VP of Science": "Irem Turkan 🇨🇾",
  },
  {
    Term: "2020/2021",
    President: "Ali Theyab 🇮🇶",
    "VP of Internal Affairs": "Julien Issa 🇱🇧",
    "VP of Finances": "Felix Behnke 🇩🇪",
    "VP of Public Relations": "Silvi Domnori 🇦🇱",
    "VP of Exchanges": "Arsal Subbah Sadiq 🇵🇰",
    "VP of Science": "Huthaifa Abdul Qader 🇯🇴",
  },
  {
    Term: "2019/2020",
    President: "Björn Bierlich 🇩🇪",
    "VP of Internal Affairs": "Greta Keršytė 🇱🇹",
    "VP of Finances": "Racem Abid 🇹🇳",
    "VP of Public Relations": "Ziva Antolin 🇸🇮",
    "VP of Exchanges": "Byung Chan Kim 🇮🇹",
    "VP of Science": "Huthaifa Abdul Qader 🇯🇴",
  },
  {
    Term: "2018/2019",
    President: "Ave Põld 🇪🇪",
    "VP of Internal Affairs": "Abanob Riad 🇪🇬",
    "VP of Finances": "Björn Bierlich 🇩🇪",
    "VP of Public Relations": "Greta Keršytė 🇱🇹",
    "VP of Exchanges": "Mustafa Hacılar 🇨🇾",
    "VP of Science": "Wun Ting Lin 🇹🇼",
  },
  {
    Term: "2017/2018",
    President: "Andrey Baltaev 🇷🇺",
    "VP of Internal Affairs": "Natalia Savkova 🇸🇰",
    "VP of Finances": "Marc-Antoine Balas 🇫🇷",
    "VP of Public Relations": "Abanob Riad 🇪🇬",
    "VP of Exchanges": "Tan Sze Hao 🇲🇾",
    "VP of Science": "Shayan Darvish 🇮🇷",
  },
  {
    Term: "2016/2017",
    President: "Sina Saygili 🇹🇷",
    "VP of Internal Affairs": "Andrey Baltaev 🇷🇺",
    "VP of Finances": "Ivo Domagala 🇵🇱",
    "VP of Public Relations": "Abanob Riad 🇪🇬",
    "VP of Exchanges": "Lucas Caponi 🇮🇹",
    "VP of Science": "Natalia Savkova 🇸🇰",
  },
  {
    Term: "2015/2016",
    President: "Malek Ghorbel 🇹🇳",
    "VP of Internal Affairs": "Sina Saygili 🇹🇷",
    "VP of Finances": "Ivo Domagala 🇵🇱",
    "VP of Public Relations": "Thanakom Thimkam 🇹🇭",
    "VP of Exchanges": "Omar Albairat 🇲🇦",
    "VP of Science": "Andrey Baltaev 🇷🇺",
  },
  {
    Term: "2014/2015",
    President: "Petra Horakova 🇨🇿",
    "VP of Internal Affairs": "Murad Alrashedi 🇸🇦",
    "VP of Finances": "Sina Saygili 🇹🇷",
    "VP of Public Relations": "Malek Ghorbel 🇹🇳",
    "VP of Exchanges": "Esti Riyanda 🇮🇩",
    "VP of Science": "Mahmoud Majzoob 🇸🇩",
  },
  {
    Term: "2013/2014",
    President: "Pavel Scarlat 🇷🇴",
    "VP of Internal Affairs": "Petra Horakova 🇨🇿",
    "VP of Finances": "Sina Saygili 🇹🇷",
    "VP of Public Relations": "Malek Ghorbel 🇹🇳",
    "VP of Exchanges": "Esti Riyanda 🇮🇩",
    "VP of Science": "Görkem Şengün 🇹🇷",
  },
  {
    Term: "2012/2013",
    President: "Pavel Scarlat 🇷🇴",
    "VP of Internal Affairs": "Nada Uncianschi 🇷🇴",
    "VP of Finances": "Artjom Meier 🇩🇪",
    "VP of Public Relations": "Petra Horakova 🇨🇿",
    "VP of Exchanges": "Belal Hedaya 🇪🇬",
    "VP of Science": "Kateřina Miklišová  🇨🇿   Tatiana Vorovchenko 🇷🇺",
  },
  {
    Term: "2011/2012",
    President: "Stefánia Zsuzsanna Radó 🇭🇺",
    "VP of Internal Affairs": "Pavel Scarlat 🇷🇴",
    "VP of Finances": "Babak Sayahpour 🇩🇪",
    "VP of Public Relations": "Karolína Floryková 🇨🇿",
    "VP of Exchanges": "Cristiana Focseneanu 🇷🇴",
    "VP of Science": "Magdalena Wilczak 🇵🇱",
  },
  {
    Term: "2010/2011",
    President: "Ionut Luchian 🇷🇴",
    "VP of Internal Affairs": "Stefánia Zsuzsanna Radó 🇭🇺",
    "VP of Finances": "Babak Sayahpour 🇩🇪",
    "VP of Public Relations": "Karolína Floryková 🇨🇿",
    "VP of Exchanges": "Lena Malaty 🇪🇬",
    "VP of Science": "Pavel Scarlat 🇷🇴",
  },
  {
    Term: "2009/2010",
    President: "Tomaz Spindler 🇸🇮",
    "VP of Internal Affairs": "Zeyad Salem 🇪🇬",
    "VP of Finances": "Amir Elkholy 🇪🇬",
    "VP of Public Relations": "Goce Naunov 🇲🇰",
    "VP of Exchanges": "Aneta Filipiuk 🇵🇱",
    "VP of Science": "Ionut Luchian 🇷🇴                Pavel Scarlat 🇷🇴",
  },
  {
    Term: "2008/2009",
    President: "Tomaz Spindler 🇸🇮",
    "VP of Internal Affairs": "Magdalena Maciejowska 🇵🇱",
    "VP of Finances": "Amir Elkholy 🇪🇬",
    "VP of Public Relations": "Zeyad Salem 🇪🇬",
    "VP of Exchanges": "Aneta Filipiuk 🇵🇱",
    "VP of Science": "Andreea Ionica 🇷🇴",
  },
  {
    Term: "2007/2008",
    President: "Juliane Gnoth 🇩🇪",
    "VP of Internal Affairs": "Magdalena Maciejowska 🇵🇱",
    "VP of Finances": "Tomaz Spindler 🇸🇮",
    "VP of Public Relations": "Michael Ermer 🇩🇪",
    "VP of Exchanges": "Natasa Predin 🇷🇸",
    "VP of Science": "N/A",
  },
  {
    Term: "2006/2007",
    President: "Andrea Veitova 🇨🇿",
    "VP of Internal Affairs": "Juliane Gnoth 🇩🇪",
    "VP of Finances": "Valeri Nadirashvili 🇬🇪",
    "VP of Public Relations": "Michael Ermer 🇩🇪",
    "VP of Exchanges": "Magdalena Maciejowska 🇵🇱",
    "VP of Science": "N/A",
  },
  {
    Term: "2005/2006",
    President: "Andrea Veitova 🇨🇿",
    "VP of Internal Affairs": "Taylan Açne 🇹🇷",
    "VP of Finances": "Nina Kotnik 🇸🇮",
    "VP of Public Relations": "Alexander Sokolovski 🇩🇪",
    "VP of Exchanges": "Ahmed Hagelsafi 🇸🇩",
    "VP of Science": "N/A",
  },
  {
    Term: "2004/2005",
    President: "Mark Antal 🇭🇺",
    "VP of Internal Affairs": "Andrea Veitova 🇨🇿",
    "VP of Finances": "Ahmed Hawas 🇪🇬",
    "VP of Public Relations": "Jörn Wittig 🇩🇪",
    "VP of Exchanges": "Ana Zulijani 🇭🇷",
    "VP of Science": "N/A",
  },
  {
    Term: "2003/2004",
    President: "Taskin Tuna 🇩🇪",
    "VP of Internal Affairs": "Ahmed Hawas 🇪🇬",
    "VP of Finances": "Jörn Wittig 🇩🇪",
    "VP of Public Relations": "Mark Antal 🇭🇺",
    "VP of Exchanges": "Ivana Boras 🇸🇮",
    "VP of Science": "N/A",
  },
  {
    Term: "2002/2003",
    President: "Iwona Olszewska 🇵🇱",
    "VP of Internal Affairs": "Ahmed Hawas 🇪🇬",
    "VP of Finances": "Hitesh Panchal 🇬🇧",
    "VP of Public Relations": "Karem Salah 🇪🇬",
    "VP of Exchanges": "Taskin Tuna 🇩🇪",
    "VP of Science": "N/A",
  },
  {
    Term: "2001/2002",
    President: "Onur Kadioğlu 🇹🇷",
    "VP of Internal Affairs": "Steffen Lauritzen 🇩🇰",
    "VP of Finances": "Hitesh Panchal 🇬🇧",
    "VP of Public Relations": "Aleksandar Necakovski 🇲🇰",
    "VP of Exchanges": "Iwona Olszewska 🇵🇱",
    "VP of Science": "N/A",
  },
  {
    Term: "2000/2001",
    President: "Sarkis Sozkes 🇹🇷",
    "VP of Internal Affairs": "Onur Kadioğlu 🇹🇷",
    "VP of Finances": "Christian Gauchi 🇲🇹",
    "VP of Public Relations": "Nina Trolle 🇸🇪",
    "VP of Exchanges": "Sofia Dias 🇳🇴",
    "VP of Science": "N/A",
  },
  {
    Term: "1999/2000",
    President: "Sarkis Sozkes 🇹🇷",
    "VP of Internal Affairs": "Onur Kadioğlu 🇹🇷",
    "VP of Finances": "Christian Gauchi 🇲🇹",
    "VP of Public Relations": "Nina Trolle 🇸🇪",
    "VP of Exchanges": "Sofia Dias 🇳🇴",
    "VP of Science": "N/A",
  },
  {
    Term: "1998/1999",
    President: "Christopher Orr 🇬🇧",
    "VP of Internal Affairs": "Sarkis Sozkes 🇹🇷",
    "VP of Finances": "Melissa Robson 🇬🇧",
    "VP of Public Relations": "Onur Kadioğlu 🇹🇷",
    "VP of Exchanges": "Eszster Somogyi 🇭🇺",
    "VP of Science": "N/A",
  },
  {
    Term: "1997/1998",
    President: "Valentina Sterjova 🇲🇰",
    "VP of Internal Affairs": "Rosana Hanke 🇵🇷",
    "VP of Finances": "Maja Cede 🇸🇮",
    "VP of Public Relations": "VACANT ⚠️",
    "VP of Exchanges": "Anamaria Stanescu 🇸🇪",
    "VP of Science": "N/A",
  },
  {
    Term: "1996/1997",
    President: "Christopher Orr 🇬🇧",
    "VP of Internal Affairs": "Alpa Choudrie 🇳🇴",
    "VP of Finances": "Maja Cede 🇸🇮",
    "VP of Public Relations": "Valentina Sterjova 🇲🇰",
    "VP of Exchanges": "Fredrik Ahlgren 🇸🇪",
    "VP of Science": "N/A",
  },
  {
    Term: "1995/1996",
    President: "Christopher Orr 🇬🇧",
    "VP of Internal Affairs": "Lizbeth Colon 🇵🇷",
    "VP of Finances": "Isabelle Portenier 🇨🇭",
    "VP of Public Relations": "Maria Lessani 🇬🇧",
    "VP of Exchanges": "Andres Izquierdo 🇨🇭",
    "VP of Science": "N/A",
  },
  {
    Term: "1994/1995",
    President: "Christopher Orr 🇬🇧",
    "VP of Internal Affairs": "Dan Rowoth 🇩🇰",
    "VP of Finances": "Isabelle Portenier 🇨🇭",
    "VP of Public Relations": "Zsuzsanna Laki 🇭🇺",
    "VP of Exchanges": "Christopher Orr 🇬🇧",
    "VP of Science": "N/A",
  },
  {
    Term: "1993/1994",
    President: "Eric Normand 🇫🇷",
    "VP of Internal Affairs": "Eva Nilson 🇸🇪",
    "VP of Finances": "Sally Eapen 🇬🇧",
    "VP of Public Relations": "Maribel Santos 🇵🇷",
    "VP of Exchanges": "Zsuzsanna Laki 🇭🇺",
    "VP of Science": "N/A",
  },
  {
    Term: "1992/1993",
    President: "Andy Boiangiu 🇮🇱",
    "VP of Internal Affairs": "Unknown",
    "VP of Finances": "Unknown",
    "VP of Public Relations": "Unknown",
    "VP of Exchanges": "Unknown",
    "VP of Science": "N/A",
  },
  {
    Term: "1988/1989",
    President: "Steven Smith 🇬🇧",
    "VP of Internal Affairs": "Unknown",
    "VP of Finances": "Unknown",
    "VP of Public Relations": "Unknown",
    "VP of Exchanges": "Unknown",
    "VP of Science": "N/A",
  },
  {
    Term: "1987/1988",
    President: "Shahul Hamed 🇸🇬",
    "VP of Internal Affairs": "Unknown",
    "VP of Finances": "Unknown",
    "VP of Public Relations": "Asegir Sigurdsson 🇮🇸",
    "VP of Exchanges": "Ami Smidt 🇮🇱",
    "VP of Science": "N/A",
  },
  {
    Term: "1986/1987",
    President: "Carlos Castro 🇵🇷",
    "VP of Internal Affairs": "Unknown",
    "VP of Finances": "Unknown",
    "VP of Public Relations": "Elisabetta Cotti 🇮🇹",
    "VP of Exchanges": "Unknown",
    "VP of Science": "N/A",
  },
  {
    Term: "1985/1986",
    President: "Robert Sicurelli Jr 🇺🇸",
    "VP of Internal Affairs": "Unknown",
    "VP of Finances": "Unknown",
    "VP of Public Relations": "Elisabetta Cotti 🇮🇹",
    "VP of Exchanges": "Unknown",
    "VP of Science": "N/A",
  },
  {
    Term: "1980/1981",
    President: "Nitzan Bitchacho 🇮🇱",
    "VP of Internal Affairs": "Unknown",
    "VP of Finances": "Unknown",
    "VP of Public Relations": "Unknown",
    "VP of Exchanges": "Unknown",
    "VP of Science": "N/A",
  },
  {
    Term: "1979/1980",
    President: "Wojieck Kowalski 🇵🇱",
    "VP of Internal Affairs": "Unknown",
    "VP of Finances": "Unknown",
    "VP of Public Relations": "Unknown",
    "VP of Exchanges": "Unknown",
    "VP of Science": "N/A",
  },
  {
    Term: "1977/1978",
    President: "Asterious Doukadis 🇬🇷",
    "VP of Internal Affairs": "Unknown",
    "VP of Finances": "Unknown",
    "VP of Public Relations": "Unknown",
    "VP of Exchanges": "Unknown",
    "VP of Science": "N/A",
  },
  {
    Term: "1976/1977",
    President: "Christopher Sanderson 🇬🇧",
    "VP of Internal Affairs": "Carsten Langemark 🇩🇰",
    "VP of Finances": "Urs Widmer 🇨🇭",
    "VP of Public Relations": "Asterious Doukadis 🇬🇷",
    "VP of Exchanges": "Chassiel Seltzer 🇮🇱",
    "VP of Science": "N/A",
  },
  {
    Term: "1975/1976",
    President: "Pantelis Bochlogyros 🇬🇷",
    "VP of Internal Affairs": "Unknown",
    "VP of Finances": "Asterious Doukadis 🇬🇷",
    "VP of Public Relations": "Asterious Doukadis 🇬🇷",
    "VP of Exchanges": "Unknown",
    "VP of Science": "N/A",
  },
  {
    Term: "1974/1975",
    President: "Shimon Friedman 🇮🇱 🇺🇸",
    "VP of Internal Affairs": "Patrick Bower 🇬🇧",
    "VP of Finances": "Raymon Bloch 🇨🇭",
    "VP of Public Relations": "Pantelis Bochlogyros 🇬🇷",
    "VP of Exchanges": "Sheila Diamond 🇬🇧",
    "VP of Science": "N/A",
  },
  {
    Term: "1973/1974",
    President: "Patrick Bower 🇬🇧",
    "VP of Internal Affairs": "Peter Stevenson-More 🇬🇧",
    "VP of Finances": "Unknown",
    "VP of Public Relations": "Unknown",
    "VP of Exchanges": "Unknown",
    "VP of Science": "N/A",
  },
  {
    Term: "1972/1973",
    President: "Ulla Jacobson 🇸🇪",
    "VP of Internal Affairs": "Itai Bab 🇮🇱",
    "VP of Finances": "Thomas Humme 🇩🇪",
    "VP of Public Relations": "Richer Silvera 🇺🇸",
    "VP of Exchanges": "Annu Heikkila 🇫🇮",
    "VP of Science": "N/A",
  },
  {
    Term: "1971/1972",
    President: "Stein Oppedal 🇳🇴",
    "VP of Internal Affairs": "Peter Stevenson-More 🇬🇧",
    "VP of Finances": "Jack Dekker 🇳🇱",
    "VP of Public Relations": "Jukka Meurman 🇫🇮",
    "VP of Exchanges": "Mark-John Vella Bardon 🇲🇹",
    "VP of Science": "N/A",
  },
  {
    Term: "1970/1971",
    President: "Torben Winkler 🇩🇰",
    "VP of Internal Affairs": "Brigida Olausson 🇸🇪",
    "VP of Finances": "Stein Oppedal 🇳🇴",
    "VP of Public Relations": "Jukka Meurman 🇫🇮",
    "VP of Exchanges": "Anya Vinanen 🇫🇮",
    "VP of Science": "N/A",
  },
  {
    Term: "1969/1970",
    President: "Aase Moller 🇩🇰",
    "VP of Internal Affairs": "Dan Nathanson 🇮🇱",
    "VP of Finances": "Torben Winkler 🇩🇰",
    "VP of Public Relations": "Brian McMullen 🇬🇧",
    "VP of Exchanges": "Suatopluk Loyka 🇨🇿",
    "VP of Science": "N/A",
  },
  {
    Term: "1968/1969",
    President: "Joop Advokaat 🇳🇱",
    "VP of Internal Affairs": "Aase Moller Hansen 🇩🇰",
    "VP of Finances": "Gerrit 🇳🇱",
    "VP of Public Relations": "Brian McMullen 🇬🇧",
    "VP of Exchanges": "Michael McGill 🇬🇧",
    "VP of Science": "N/A",
  },
  {
    Term: "1967/1968",
    President: "Sylvia Theaker 🇬🇧",
    "VP of Internal Affairs": "Unknown",
    "VP of Finances": "Unknown",
    "VP of Public Relations": "Brian McMullen 🇬🇧",
    "VP of Exchanges": "Michael McGill 🇬🇧",
    "VP of Science": "N/A",
  },
  {
    Term: "1966/1967 ",
    President: "Inger Gutestam 🇸🇪",
    "VP of Internal Affairs": "Sylvia Theaker 🇬🇧",
    "VP of Finances": "Peter Swiss 🇬🇧",
    "VP of Public Relations": "Unknown",
    "VP of Exchanges": "Unknown",
    "VP of Science": "N/A",
  },
  {
    Term: "1951/1952",
    President: "Leslie Sorling 🇸🇪",
    "VP of Internal Affairs": "Mogens Skougard 🇩🇰",
    "VP of Finances": "Carlo Nevejan 🇳🇱",
    "VP of Public Relations": "N/A",
    "VP of Exchanges": "N/A",
    "VP of Science": "N/A",
  },
];

export default PrevExecCom;
