const delegatesList = [
  {
    Country: "Albania",
    "Member Organization": "Brainstorm Organization",
    Abbreviation: "BRST ORG",
    "Membership Status": "Full Country",
    "Delegate Name": "Ersid Domnori",
  },
  {
    Country: "Australia",
    "Member Organization": "Australian Dental Students' Association",
    Abbreviation: "ADSA",
    "Membership Status": "Full Country",
    "Delegate Name": "Emma Turner",
  },
  {
    Country: "Bangladesh",
    "Member Organization": "Dhaka Dental College Debating & Quiz Society",
    Abbreviation: "DDC DQS",
    "Membership Status": "Corresponding Local",
    "Delegate Name": "Md Ahnaf M Rahman Rito",
  },
  {
    Country: "Benin",
    "Member Organization": "Benin's Odonto-Stomatology Students Association",
    Abbreviation: "BOSSA",
    "Membership Status": "Corresponding",
    "Delegate Name": "Justine DA AROYNARD",
  },
  {
    Country: "Bulgaria",
    "Member Organization": "Bulgarian Dental Students' Association",
    Abbreviation: "BASDM",
    "Membership Status": "Corresponding",
    "Delegate Name": "Anife Suleymanova",
  },
  {
    Country: "Burkina Faso",
    "Member Organization":
      "Association des Étudiants en Chirurgie Dentaire du Burkina Faso",
    Abbreviation: "AECD-BF",
    "Membership Status": "Affiliate National",
    "Delegate Name": "Laure Tresorier",
  },
  {
    Country: "Cambodia ",
    "Member Organization": "Cambodia Dental Students’ Association ",
    Abbreviation: "CDSA",
    "Membership Status": "Affiliate ",
    "Delegate Name": "Soeun Senghor ",
  },
  {
    Country: "Canada",
    "Member Organization": "Federation of Canadian Dental Student Associations",
    Abbreviation: "FCDSA",
    "Membership Status": "Corresponding",
    "Delegate Name": "Jacques Jaar",
  },
  {
    Country: "Chile",
    "Member Organization":
      "Asociacion Nacional Científica de Estudiantes de Odontología",
    Abbreviation: "ANACEO",
    "Membership Status": "Affiliate",
    "Delegate Name": "Juan Pablo Aravena",
  },
  {
    Country: "Colombia",
    "Member Organization":
      "Semilleros de investigación facultad de Odontología",
    Abbreviation: "UBSIFO",
    "Membership Status": "Full Local",
    "Delegate Name": "Hernán Socarrás Bohórquez",
  },
  {
    Country: "Croatia",
    "Member Organization":
      "Croatian Association of Dental Students for International Activities and Exchange",
    Abbreviation: "CroADS",
    "Membership Status": "Full Local",
    "Delegate Name": "Valentina Marasović",
  },
  {
    Country: "Czech Republic",
    "Member Organization": "Czech Dental Student Association",
    Abbreviation: "SSSČR",
    "Membership Status": "Full Country",
    "Delegate Name": "Zuzana Kadlečíková",
  },
  {
    Country: "Ecuador",
    "Member Organization": "Ecuadorian Organization of Dental Students",
    Abbreviation: " OEEO",
    "Membership Status": "Affiliate National",
    "Delegate Name": "Jorge David Ayala Alava",
  },
  {
    Country: "Egypt",
    "Member Organization": "Dental Students’ Scientific Association of Egypt",
    Abbreviation: "DSSA-Egypt",
    "Membership Status": "Full Country ",
    "Delegate Name": "Merna Maher Fekry Gress",
  },
  {
    Country: "Fiji",
    "Member Organization": "Fiji Dental Students' Association",
    Abbreviation: "FDSA",
    "Membership Status": "Affiliate",
    "Delegate Name": "Kartik Kishore Rathod",
  },
  {
    Country: "Finland",
    "Member Organization": "Suomen Hammaslääketieteen Opiskelijain Liitto ry",
    Abbreviation: "SHOL ry",
    "Membership Status": "Full Country",
    "Delegate Name": "Ella Liinamaa",
  },
  {
    Country: "France",
    "Member Organization":
      "Union Nationale des Etudiants en Chirurgie Dentaire",
    Abbreviation: "UNECD",
    "Membership Status": "Full Country",
    "Delegate Name": "Charlotte Carter",
  },
  {
    Country: "Germany",
    "Member Organization": "Zahnmedizinischer Austauschdienst",
    Abbreviation: "ZAD",
    "Membership Status": "Full Country",
    "Delegate Name": "Jasmin Mansournia",
  },
  {
    Country: "India",
    "Member Organization": "Indian Association of Dental Students",
    Abbreviation: "IADSINDIA",
    "Membership Status": "Full Country",
    "Delegate Name": "Praveen Singh",
  },
  {
    Country: "Indonesia ",
    "Member Organization":
      "Persatun Senat Mahasiswa Kedoktean Gigi  Indonesia ",
    Abbreviation: "PSMKGI ",
    "Membership Status": "Full Country ",
    "Delegate Name": "Maulida Nurhasanah ",
  },
  {
    Country: "Iran",
    "Member Organization": "Dental Students' Scientific Research Center",
    Abbreviation: "DSSRC ",
    "Membership Status": "Full National",
    "Delegate Name": "Ailar Yousefbeigi ",
  },
  {
    Country: "Iraq",
    "Member Organization": "Iraqi Dental Students Association",
    Abbreviation: "IDSA",
    "Membership Status": "Full Country ",
    "Delegate Name": "Noor Sarmad",
  },
  {
    Country: "Israel",
    "Member Organization": "Federation of Israeli Dental Students",
    Abbreviation: "FIDS",
    "Membership Status": "Full Country",
    "Delegate Name": "Noy Saar",
  },
  {
    Country: "Italy",
    "Member Organization": "Associazione Italiana Studenti Odontoiatria",
    Abbreviation: "AISO",
    "Membership Status": "Full Country",
    "Delegate Name": "Anita Homayuni",
  },
  {
    Country: "Ivory Coast",
    "Member Organization":
      "National Organization of Health Sciences Students' - ODONTOSTOMATOLOGIE",
    Abbreviation: "NOHSS-ODONTOSTOMATOLOGIE",
    "Membership Status": "Corresponding",
    "Delegate Name": "Constantin ZOGBE",
  },
  {
    Country: "Japan",
    "Member Organization": "Japan Dental Students Association",
    Abbreviation: "JDSA",
    "Membership Status": "Full Country ",
    "Delegate Name": "Mizuki Tawa ",
  },
  {
    Country: "Jordan",
    "Member Organization": "Jordanian Association of Dental Students",
    Abbreviation: "JADS",
    "Membership Status": "Full National",
    "Delegate Name": "Yasmeen Al-Jarrah",
  },
  {
    Country: "Kazakstan ",
    "Member Organization": "Kazakstan Association of Dental Youth",
    Abbreviation: "KADY",
    "Membership Status": "Full Country",
    "Delegate Name": "Zhengis Zhamashev",
  },
  {
    Country: "Kurdistan",
    "Member Organization": "Kurdistan Dental Health Organization",
    Abbreviation: "KDHO",
    "Membership Status": "Full Local",
    "Delegate Name": "Zerrin Kamaran",
  },
  {
    Country: "Latvia",
    "Member Organization": "Latvian Dental Students Association ",
    Abbreviation: "LDSA",
    "Membership Status": "Full Country ",
    "Delegate Name": "Kristīne Romanovska",
  },
  {
    Country: "Lebanon",
    "Member Organization": "Lebanese Association of Dental Students",
    Abbreviation: "LADS",
    "Membership Status": "Full National",
    "Delegate Name": "Ismail Rifai",
  },
  {
    Country: "Lithuania",
    "Member Organization": "Studentų Odontologų Associacija",
    Abbreviation: "SOA",
    "Membership Status": "Full Country",
    "Delegate Name": "Kristė Trijonytė",
  },
  {
    Country: "Lybia",
    "Member Organization":
      "Libyan Dental Students and Young Dentists Association",
    Abbreviation: "LDSA",
    "Membership Status": "Full National",
    "Delegate Name": "Wisam ALARBI",
  },
  {
    Country: "Malaysia",
    "Member Organization": "Malaysian Dental Students’ Association ",
    Abbreviation: "MDSA",
    "Membership Status": "Full Country",
    "Delegate Name": "Lee Chin Sheng",
  },
  {
    Country: "Moldova",
    "Member Organization": "Moldovan Dental Students' Association",
    Abbreviation: "MDSA",
    "Membership Status": "Corresponding",
    "Delegate Name": "Mogildea Maria",
  },
  {
    Country: "Morocco",
    "Member Organization": "Um6ss Smile Creators Association ",
    Abbreviation: "USCA",
    "Membership Status": "Full Local",
    "Delegate Name": "BELLAQ Wissal",
  },
  {
    Country: "Morocco",
    "Member Organization":
      "Association Ibn Sina des Etudiants en Médecine Dentaire de Rabat",
    Abbreviation: "Ibn Sina",
    "Membership Status": "Full Local ",
    "Delegate Name": "",
  },
  {
    Country: "Nepal",
    "Member Organization": "Nepal Dental Student Association",
    Abbreviation: "NDSA",
    "Membership Status": "Corresponding",
    "Delegate Name": "Irfan Reza",
  },
  {
    Country: "Northern Cyprus ",
    "Member Organization": "Northern Cyprus Association of Dental Students",
    Abbreviation: "NCADS",
    "Membership Status": "Full Country (Associate member)",
    "Delegate Name": "Serpil Çiftçioğlu",
  },
  {
    Country: "Pakistan",
    "Member Organization": "Pakistan Association of Dental Students",
    Abbreviation: "PADS",
    "Membership Status": "Full Country ",
    "Delegate Name": "Aneeqa Aslam",
  },
  {
    Country: "Palestine",
    "Member Organization": "Palestinian Association of Dental Students",
    Abbreviation: "PADS",
    "Membership Status": "Full Country",
    "Delegate Name": "Mohammad Zakout",
  },
  {
    Country: "Philippine ",
    "Member Organization": "Philippine Dental Students Association",
    Abbreviation: "PDSA",
    "Membership Status": "Full Country ",
    "Delegate Name": "Janel Christine Mendoza ",
  },
  {
    Country: "Poland",
    "Member Organization": "Polish Association of Dental Students",
    Abbreviation: "PTSS",
    "Membership Status": "Full Country",
    "Delegate Name": "Michał Dudziński",
  },
  {
    Country: "Portugal",
    "Member Organization": "Portuguese Dental Students Association",
    Abbreviation: "ANEMD",
    "Membership Status": "Full Country",
    "Delegate Name": "António Coimbra Amaral",
  },
  {
    Country: "Romania",
    "Member Organization": "Liga Studentilor la Medicina Dentara Bucuresti",
    Abbreviation: "LSMDB",
    "Membership Status": "Full Local",
    "Delegate Name": "Ana Stefanescu",
  },
  {
    Country: "Romania",
    "Member Organization": "Societatea Studentilor Stomatologi Craiova",
    Abbreviation: "SSSC",
    "Membership Status": "Full Local",
    "Delegate Name": "Andreea Olteanu",
  },
  {
    Country: "Romania",
    "Member Organization": "Societatea Studentilor Stomatologi Iasi",
    Abbreviation: "SSSI",
    "Membership Status": "Full Local",
    "Delegate Name": "Larisa-Maria Ungureanu",
  },
  {
    Country: "Russia",
    "Member Organization": "National Medical Students' State",
    Abbreviation: "HCCM",
    "Membership Status": "Full Country",
    "Delegate Name": "Tatiana Spitsyna",
  },
  {
    Country: "Russia",
    "Member Organization":
      "Russian Association of Dental Students and Young Dentists",
    Abbreviation: "RADSYD",
    "Membership Status": "Full Local (Associate member)",
    "Delegate Name": "Anastasia Romanova",
  },
  {
    Country: "Rwanda",
    "Member Organization": "Rwanda Dental Students' Association",
    Abbreviation: "RDSA",
    "Membership Status": "Affiliate",
    "Delegate Name": "",
  },
  {
    Country: "Senegal",
    "Member Organization":
      "Association Des Etudiants Chirurgiens Dentistes Du Senegal",
    Abbreviation: "AECDS",
    "Membership Status": "Corresponding",
    "Delegate Name": "Abdoulaye Amath DIOP",
  },
  {
    Country: "Slovakia",
    "Member Organization": "Slovenský Spolok Študentov Zubného Lekárstva",
    Abbreviation: "SSSZL",
    "Membership Status": "Full Country",
    "Delegate Name": "Katarina Vendelova",
  },
  {
    Country: "Slovenia",
    "Member Organization": "Slovenian dental students International Committee",
    Abbreviation: "SiDSIC",
    "Membership Status": "Full Country",
    "Delegate Name": "Tjaša Miklavčič",
  },
  {
    Country: "Sudan",
    "Member Organization": "Sudanese Association Of Dental Students",
    Abbreviation: "SADS",
    "Membership Status": "Full Country",
    "Delegate Name": "Ahmed Yasir",
  },
  {
    Country: "Sweden",
    "Member Organization": "Swedish Dental Students Association",
    Abbreviation: "SDSA",
    "Membership Status": "Full Country",
    "Delegate Name": "Viktoria Réthy",
  },
  {
    Country: "Taiwan",
    "Member Organization": "Taiwan Dental Student Association ",
    Abbreviation: "TDSA",
    "Membership Status": "Full Country ",
    "Delegate Name": "Chen-Yun Kao ",
  },
  {
    Country: "Tanzania",
    "Member Organization": "Tanzanian Dental Students Association ",
    Abbreviation: "TDSA",
    "Membership Status": "Affiliate ",
    "Delegate Name": "Sales nicco",
  },
  {
    Country: "Thailand ",
    "Member Organization": "Dental Student Association of Thailand",
    Abbreviation: "DSAT",
    "Membership Status": "Full Country ",
    "Delegate Name": "Thamasorn Eamtanaporn ",
  },
  {
    Country: "Tunisia",
    "Member Organization": "Tunisian Dental Students Association ",
    Abbreviation: "TDSA",
    "Membership Status": "Full National",
    "Delegate Name": "Samar Herchi",
  },
  {
    Country: "Turkey",
    "Member Organization": "Turkish Dental Students International Committee",
    Abbreviation: "",
    "Membership Status": "Full Country",
    "Delegate Name": "Asmin Seran Özbek ",
  },
  {
    Country: "UAE ",
    "Member Organization": "University of Sharjah Dental Student Association",
    Abbreviation: "USDSA",
    "Membership Status": "Full Local",
    "Delegate Name": "Zumurd al Anoud ",
  },
  {
    Country: "Ukraine",
    "Member Organization": "MEDICAL STUDENTS UNION",
    Abbreviation: "MSU",
    "Membership Status": "Corresponding Local",
    "Delegate Name": "Viktoriia Sosnova",
  },
  {
    Country: "Zimbabwe",
    "Member Organization": "Zimbabwe Dental Students Association",
    Abbreviation: "ZiDSA",
    "Membership Status": "Full Country",
    "Delegate Name": "Takunda Tracy Machera",
  },
];

export default delegatesList;
